package com.carrental.domain;

public enum ResponseKeys {
  STATUS,
  EXCEPTION_TYPE,
  EXCEPTION_MESSAGE,
  CAR,
  CAR_LIST,
  CAR_DELETED,
  RENTAL,
  RENTAL_LIST,
  RENTAL_DELETED,
  MAINTENANCE,
  MAINTENANCE_LIST,
  MAINTENANCE_DELETED,
  CONTACT,
  CONTACT_LIST,
  CONTACT_DELETED
}
